stages: [test, report]

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.default_job_template: &defaults
  stage: test
  tags: ['mac']
  before_script:
    - node -v && npm -v
    - npm ci || npm i
    - mkdir -p allure-results errorShots
    - rm -rf allure-results allure-report # <- Retirar se falha
    - mkdir -p allure-results errorShots # <- Retirar se falha
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - allure-results/
      - errorShots/

android_tests:
  <<: *defaults
  script:
    - npm run android || true
  after_script:
    - npx allure generate --clean allure-results -o allure-report || true

ios_tests:
  <<: *defaults
  rules:
    - if: $RUN_IOS == "1"
    - when: manual
  script:
    - npm run ios || true
  after_script:
    - npx allure generate --clean allure-results -o allure-report || true

generate_allure_report:
  stage: report
  tags: ['mac']
  needs: ['android_tests']
  script:
    - npm install -g allure-commandline
    - allure generate --clean allure-results -o allure-report || true
  artifacts:
    when: always
    paths:
      - allure-report/
    expire_in: 30 days
